In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1]) 

2


In [3]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3]) 

7


In [4]:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2]) 

6


In [5]:
# utilizando dtype


arr = np.array([1, 2, 3, 4])

print(arr.dtype) 

int64


In [6]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x) 

[42  2  3  4  5]
[42  2  3  4  5]


In [7]:
#exemplo de uso de shape
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape) 

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [8]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x) 

1
2
3


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x) 

[1 2 3]
[4 5 6]


In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y) 

1
2
3
4
5
6


In [11]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z) 

1
2
3
4
5
6
7
8
9
10
11
12


In [12]:
#juntando dois arrays 

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr) 

[1 2 3 4 5 6]


In [13]:
# Procurando valores dentro de um array

In [14]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x) 

(array([3, 5, 6]),)


In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x) 

(array([1, 3, 5, 7]),)


In [16]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x) 

[1 2 3]
